# Generated by Django 2.1.7 on 2019-03-05 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=200)),
                ('locationAddress', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userNickname', models.CharField(max_length=100)),
                ('userName', models.CharField(max_length=200)),
                ('userMail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='sport',
            name='users',
            field=models.ManyToManyField(to='M2P.User'),
        ),
        migrations.AddField(
            model_name='location',
            name='sports',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='M2P.Sport'),
        ),
    ]
