# Generated by Django 2.1.7 on 2019-03-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M2P', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetime',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datetime',
            name='dateTime',
            field=models.DateTimeField(),
        ),
    ]
