# Generated by Django 2.1.7 on 2019-03-24 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('M2P', '0002_auto_20190324_2239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuari',
            new_name='User',
        ),
    ]
